### ISSUE TITLE
FSR3 for UE5.4

### ISSUE THREAD

**Issue by echo-matt** [Adriwin06/Ultimate-CommonUI-Menu-System#16]
Hello, since FSR3.1 came out with support for UE5.4, are you gonna update this project?

Mainly asking because i'm in the middle of implementing both DLSS and FSR in my project and i can't have both frame generation tech on at once. I need to disable nvidia streamline plugin to let FSR Frame generation work, but that is not possible at runtime so i was wondering if there's a method to do it so that players could choose between DLSS Frame gen and FSR Frame gen

**Comment by Adriwin06** [comment]
Hi! I will update this project when I come back home this Week-end. I was already on vacation when it came out so I couldn't update it.

As for both Frame Gen, I was wondering why it wouldn't work on my RTX 4070 Super, but was working on my old RTX 3060 Ti, but you're probably right, it might be the Streamline plugin that does this, but only if DLSS 3 is supported. That's all I know. I will look into it when I can.

**Comment by echo-matt** [comment]
Thank you, i will keep an eye on this for a fix

**Comment by Adriwin06** [comment]
I updated the 5.4 branch, and FSR 3 Frame Gen works, it's just that it needs FSR upscaling to be enabled, and I didn't knew that. The problem is that even with FRS 3.1, it still needs FSR upscaling, even if they said that it didn't anymore...

Now I will merge the 5.4 branch in the main branch when I find a way to do it, because it's telling me that there is too much conflict, and I don't know how to "force" a pull request merge. I just want the main branch to be the actual 5.4 branch, and then remove the 5.4 branch...

**Comment by echo-matt** [comment]
So does FSR Frame Interpolation works with DLSS Frame generation active? As in, Streamline plugin activated and initialized? Because in my project i can't seem to make both work

**Comment by Adriwin06** [comment]
No you're right, now DLSS frame gen don't work anymore, but the FSR one does.

**Comment by echo-matt** [comment]
So i guess it's impossible to have both FG tech available at all times without restarting the game
